name = "marketflow-api"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "marketflow-db"
database_id = "1c967a44-a6c4-43e7-bdbd-2e340cac0357"
migrations_dir = "src/db/migrations"

[[durable_objects.bindings]]
name = "SYNC_DOC"
class_name = "SyncDocRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncDocRoom"]

[vars]
ENVIRONMENT = "production"
